dorado: scripts/dorado_ont.sh
pod5_env: pod5
mm10: /data1/greenbab/database/mm10/mm10.fa
hg38: /data1/greenbab/database/hg38/v0/Homo_sapiens_assembly38.fasta
# ref_genome: /data/greenbaum/database/mm10/mm10.fa
ONT_conda_env: methyl_ONT