samples:
    D-0-1: /lila/data/greenbaum/users/ahunos/TRI_EPI_DIVYA/mod_bases/D-0-1/D-0-1_5mCG_5hmCG_calls_sorted.bam
    D-0-2: /lila/data/greenbaum/users/ahunos/TRI_EPI_DIVYA/mod_bases/D-0-2/D-0-2_5mCG_5hmCG_calls_sorted.bam
    D-0-3: /lila/data/greenbaum/users/ahunos/TRI_EPI_DIVYA/mod_bases/D-0-3/D-0-3_5mCG_5hmCG_calls_sorted.bam
    D-A-1: /lila/data/greenbaum/users/ahunos/TRI_EPI_DIVYA/mod_bases/D-A-1/D-A-1_5mCG_5hmCG_calls_sorted.bam
    D-A-2: /lila/data/greenbaum/users/ahunos/TRI_EPI_DIVYA/mod_bases/D-A-2/D-A-2_5mCG_5hmCG_calls_sorted.bam
    D-A-3: /lila/data/greenbaum/users/ahunos/TRI_EPI_DIVYA/mod_bases/D-A-3/D-A-3_5mCG_5hmCG_calls_sorted.bam
