samples:
    D-0-1: /data/greenbaum/projects/ONT/projects/RERUN/TRI_EPIGENETIC/organized/FAST5/D-0-1
    D-A-1: /data/greenbaum/projects/ONT/projects/RERUN/TRI_EPIGENETIC/organized/FAST5/D-A-1

    # sampleName2: /directory/to/sample/file_2.tsv