samples:
    D-0-1_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-0-1_4000/D-0-1_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-0-1_4000/D-0-1_4000_seq_summary.txt"
    D-0-1_5000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-0-1_5000/D-0-1_5000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-0-1_5000/D-0-1_5000_seq_summary.txt"
    # D-0-1_5000_4000:
      # - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/mergedbams_modkit/results/mark_duplicates/D-0-1_5000_4000/D-0-1_5000_4000_modBaseCalls_sorted_dup.bam"
    D-0-2_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-0-2_4000/D-0-2_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-0-2_4000/D-0-2_4000_seq_summary.txt"
    D-0-2_5000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-0-2_5000/D-0-2_5000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-0-2_5000/D-0-2_5000_seq_summary.txt"
    # D-0-2_5000_4000:
    #   - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/mergedbams_modkit/results/mark_duplicates/D-0-2_5000_4000/D-0-2_5000_4000_modBaseCalls_sorted_dup.bam"
    D-0-3_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-0-3_4000/D-0-3_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-0-3_4000/D-0-3_4000_seq_summary.txt"
    D-A-1_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-A-1_4000/D-A-1_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-A-1_4000/D-A-1_4000_seq_summary.txt"
    D-A-2_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-A-2_4000/D-A-2_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-A-2_4000/D-A-2_4000_seq_summary.txt"
    D-A-3_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-A-3_4000/D-A-3_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-A-3_4000/D-A-3_4000_seq_summary.txt"
    D-C-1_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-C-1_4000/D-C-1_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-C-1_4000/D-C-1_4000_seq_summary.txt"
    D-C-2_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-C-2_4000/D-C-2_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-C-2_4000/D-C-2_4000_seq_summary.txt"
    D-C-3_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-C-3_4000/D-C-3_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-C-3_4000/D-C-3_4000_seq_summary.txt"
    D-Q-1_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-Q-1_4000/D-Q-1_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-Q-1_4000/D-Q-1_4000_seq_summary.txt"
    D-Q-1_5000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-Q-1_5000/D-Q-1_5000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-Q-1_5000/D-Q-1_5000_seq_summary.txt"
    # D-Q-1_5000_4000:
    #   - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/mergedbams_modkit/results/mark_duplicates/D-Q-1_5000_4000/D-Q-1_5000_4000_modBaseCalls_sorted_dup.bam"
    D-Q-2_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-Q-2_4000/D-Q-2_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-Q-2_4000/D-Q-2_4000_seq_summary.txt"
    D-QC-3_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-QC-3_4000/D-QC-3_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-QC-3_4000/D-QC-3_4000_seq_summary.txt"
    D-S-1_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-S-1_4000/D-S-1_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-S-1_4000/D-S-1_4000_seq_summary.txt"
    D-S-1_5000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-S-1_5000/D-S-1_5000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-S-1_5000/D-S-1_5000_seq_summary.txt"
    # D-S-1_5000_4000:
    #   - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/mergedbams_modkit/results/mark_duplicates/D-S-1_5000_4000/D-S-1_5000_4000_modBaseCalls_sorted_dup.bam"
    D-S-2_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-S-2_4000/D-S-2_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-S-2_4000/D-S-2_4000_seq_summary.txt"
    D-S-3_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-S-3_4000/D-S-3_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-S-3_4000/D-S-3_4000_seq_summary.txt"
    D-SC-1_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-SC-1_4000/D-SC-1_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-SC-1_4000/D-SC-1_4000_seq_summary.txt"
    D-SC-2_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-SC-2_4000/D-SC-2_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-SC-2_4000/D-SC-2_4000_seq_summary.txt"
    D-SC-3_4000:
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/mark_duplicates/D-SC-3_4000/D-SC-3_4000_modBaseCalls_sorted_dup.bam"
      - "/data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/results/dorado_summary/D-SC-3_4000/D-SC-3_4000_seq_summary.txt"