samples:
    D-0-1: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-0-1/D-0-1.pod5
    D-0-2: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-0-2/D-0-2.pod5
    D-0-3: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-0-3/D-0-3.pod5
    D-A-1: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-A-1/D-A-1.pod5
    D-A-2: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-A-2/D-A-2.pod5
    D-A-3: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-A-3/D-A-3.pod5
    D-C-1: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-C-1/D-C-1.pod5
    D-C-2: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-C-2/D-C-2.pod5
    D-C-3: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-C-3/D-C-3.pod5
    D-Q-1: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-Q-1/D-Q-1.pod5
    D-Q-2: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-Q-2/D-Q-2.pod5
    D-Q-3: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-Q-3/D-Q-3.pod5
    D-QC-1: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-QC-1/D-QC-1.pod5
    D-QC-2: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-QC-2/D-QC-2.pod5
    D-QC-3: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-QC-3/D-QC-3.pod5
    D-S-1: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-S-1/D-S-1.pod5
    D-S-2: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-S-2/D-S-2.pod5
    D-S-3: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-S-3/D-S-3.pod5
    D-SC-1: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-SC-1/D-SC-1.pod5
    D-SC-2: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-SC-2/D-SC-2.pod5
    D-SC-3: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/raw/TRI_DIVYA_POD5/pod5/D-SC-3/D-SC-3.pod5